// Product Model - Mock database
const products = [
     {
          id: 1,
          name: 'Premium Wireless Headphones',
          price: 199.99,
          description: 'High-quality sound with noise cancellation',
          category: 'Electronics',
          stock: 50,
          rating: 4.8,
          reviews: 124,
          image: '/products/headphones.jpg',
     },
     {
          id: 2,
          name: 'Smartwatch Pro',
          price: 299.99,
          description: 'Track your fitness with advanced features',
          category: 'Electronics',
          stock: 30,
          rating: 4.6,
          reviews: 89,
          image: '/products/smartwatch.jpg',
     },
     {
          id: 3,
          name: 'Portable Charger',
          price: 49.99,
          description: 'Fast charging for all your devices',
          category: 'Accessories',
          stock: 100,
          rating: 4.9,
          reviews: 256,
          image: '/products/charger.jpg',
     },
     {
          id: 4,
          name: 'USB-C Cable',
          price: 14.99,
          description: 'Durable and fast data transfer',
          category: 'Accessories',
          stock: 200,
          rating: 4.7,
          reviews: 412,
          image: '/products/cable.jpg',
     },
     {
          id: 5,
          name: 'Camera Backpack',
          price: 79.99,
          description: 'Protective storage for your gear',
          category: 'Bags',
          stock: 25,
          rating: 4.5,
          reviews: 67,
          image: '/products/backpack.jpg',
     },
     {
          id: 6,
          name: 'Phone Stand',
          price: 24.99,
          description: 'Adjustable stand for all phones',
          category: 'Accessories',
          stock: 150,
          rating: 4.4,
          reviews: 178,
          image: '/products/phone-stand.jpg',
     },
];

module.exports = products;
